Task_2_1_1
kkbagrryantsev/OOP pull request #13
Opened 2023-02-14 16:24 UTC by kkbagrryantsev

Road to the thread benchmark

2023-02-17 15:10 UTC, alradish requested changes

2023-02-17 15:10 UTC, alradish commented on Task_2_1_1/src/main/java/ru/nsu/kbagryantsev/ParallelStreamTask.java
> +    public static boolean main(final List<Integer> numbers) {
Всё же кажется имя тут не подходит

2023-02-17 15:10 UTC, alradish commented on Task_2_1_1/src/main/java/ru/nsu/kbagryantsev/PrimeNumbersUtils.java
> +        return numbers.stream().anyMatch(PrimeNumbersUtils::isPrime);
Вернёт тру если есть хотя бы одно простое

2023-02-17 15:10 UTC, alradish commented on Task_2_1_1/src/main/java/ru/nsu/kbagryantsev/MultiThreadedTask.java
> +            threads.add(i, new Thread(task));
Можно просто `add(new Thread(task))`

2023-02-17 15:10 UTC, alradish commented on Task_2_1_1/src/main/java/ru/nsu/kbagryantsev/MultiThreadedTask.java
> +        return result.get();
Треды могли ещё не закончить работать

2023-02-19 11:37 UTC, kkbagrryantsev commented on Task_2_1_1/src/main/java/ru/nsu/kbagryantsev/ParallelStreamTask.java
> +    public static boolean main(final List<Integer> numbers) {
Исправил на call

2023-02-19 11:38 UTC, kkbagrryantsev commented on Task_2_1_1/src/main/java/ru/nsu/kbagryantsev/PrimeNumbersUtils.java
> +        return numbers.stream().anyMatch(PrimeNumbersUtils::isPrime);
Недоглядел, уже исправлено

2023-02-19 11:38 UTC, kkbagrryantsev commented on Task_2_1_1/src/main/java/ru/nsu/kbagryantsev/MultiThreadedTask.java
> +            threads.add(i, new Thread(task));
Да, исправил

2023-02-19 11:39 UTC, kkbagrryantsev commented on Task_2_1_1/src/main/java/ru/nsu/kbagryantsev/MultiThreadedTask.java
> +        return result.get();
Вызвал join для всех тредов

2023-02-22 07:49 UTC, alradish approved these changes

2023-02-22 07:50 UTC, merged