Task_1_2_3
kkbagrryantsev/OOP pull request #8
Opened 2022-10-24 17:20 UTC by kkbagrryantsev

Road to a directed weighted graph

2022-10-27 05:07 UTC, Leidenn2509 requested changes

2022-10-27 05:07 UTC, Leidenn2509 commented on Task_1_2_3/src/main/java/ru/nsu/kbagryantsev/Vertex.java
> +    public void setVertex(V data) {
set data/value

2022-10-27 05:07 UTC, Leidenn2509 commented on Task_1_2_3/src/main/java/ru/nsu/kbagryantsev/Edge.java
> +    public void setEdge(E weight) {
setWeight

2022-10-27 05:07 UTC, Leidenn2509 commented on Task_1_2_3/src/main/java/ru/nsu/kbagryantsev/GraphUtils.java
> +        initializeSingleSource.accept(graph, init);
А точно нужно выделять код в локальную переменную? Он вызывается один раз?

2022-10-30 08:06 UTC, kkbagrryantsev commented
First committed on 24th of October

2022-10-31 11:23 UTC, alradish requested changes
- Уберите Draft

2022-10-31 11:23 UTC, alradish commented on Task_1_2_3/src/main/java/ru/nsu/kbagryantsev/GraphReader.java
> +        ArrayList<Vertex<Integer>> verticesArray;
Старайтесь использовать макимально общие интерфейсы для типов переменных

2022-10-31 11:23 UTC, alradish commented on Task_1_2_3/src/main/java/ru/nsu/kbagryantsev/GraphReader.java
> +            int end     = 0;
Не форматируйте так, не по стилям

2022-11-03 08:59 UTC, alradish approved these changes

2022-11-05 11:59 UTC, merged